backend:
  name: github
  repo: colettesnowmedia/colettesnowmedia.github.io
  branch: master
  site_domain: thirsty-swanson-e6482c.netlify.com

media_folder: "assets/images"
media_library:
  name: uploadcare
  config:
    publicKey: b76b758fbbcd64ee79b2

display_url: https://colettesnow.com
logo_url: https://colettesnow.com/assets/images/logo.png
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: "posts"
    label: "Posts"
    label_singular: "Post"
    folder: "_posts"
    delete: true
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
    - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Publication Date", name: "date", widget: "datetime"}
    - {label: "Author", name: "author", widget: "relation", collection: "authors", searchFields: ["title", "twitter", "username"], valueField: "twitter", displayFields: ["title", "username"]}
    - {label: "Categories", name: "categories", widget: "list", field: { label: "Category", widget: "relation", searchFields: ["title", "term"], valueField: "term", displayFields: ["title"], collection: "categories" }}
    - {label: "Body", name: "body", widget: "markdown"}
    - {label: "Excerpt", name: "text", widget: "string", required: false}
    - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    folder: "_pages"
    delete: true
    create: true
    slug: "{{slug}}"
    fields:
    - {label: "Layout", name: "layout", widget: "select",options: [{ label: "Default (Homepage)", value: "default" },{ label: "Page", value: "page" },{ label: "Page without Sidebar", value: "no-sidebar-page" }], default: "page"}
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Body", name: "body", widget: "markdown"}
    - {label: "Permalink", name: "permalink", widget: "string", required: false}
  - name: "categories"
    label: "Categories"
    label_singular: "Category"
    folder: "_cats"
    delete: true
    create: true
    slug: "{{slug}}"
    fields:
    - {label: "Layout", name: "layout", widget: "hidden", default: "category"}
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Term", name: "term", widget: "string"}
    - {label: "In Navigation?", name: "in_main_nav", widget: "boolean"}
    - {label: "Permalink", name: "permalink", widget: "string", required: false}
    editor:
      preview: false
  - name: "products"
    label: "Products"
    label_singular: "Product"
    folder: "products"
    delete: true
    create: true
    fields:
    - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Body", name: "body", widget: "markdown"}
  - name: "portfolio"
    label: "Portfolio Items"
    label_singular: "Portfolio Item"
    folder: "_portfolio"
    delete: true
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Thumbnail", name: "thumbnail", widget: "image"}
    - {label: "Screenshot", name: "screenshot", widget: "image"}
    - {label: "Caption", name: "caption", widget: "text"}
    - {label: "Technology", name: "technology", widget: "list"}
    - label: "Type"
      name: "type"
      widget: "select"
      options:
        - { label: "WordPress", value: "wordpress" }
        - { label: "Website (non WordPress)", value: "websites" }
        - { label: "Projects", value: "projects" }