backend:
  name: github
  repo: colettesnowmedia/colettesnowmedia.github.io
  branch: master
  site_domain: thirsty-swanson-e6482c.netlify.com

media_folder: "assets/images"
media_library:
  name: uploadcare
  config:
    publicKey: b76b758fbbcd64ee79b2

display_url: https://colettesnow.com
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: "posts"
    label: "Posts"
    label_singular: "Post"
    description: "Blog posts"
    folder: "_posts"
    delete: true
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
    - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Publication Date", name: "date", widget: "datetime"}
    - {label: "Author", name: "author", widget: "string", default: "colettesnow"}
    - {label: "Categories", name: "categories", widget: "string", default: "anime"}
    - {label: "Body", name: "body", widget: "markdown"}
    - {label: "Excerpt", name: "text", widget: "string", required: false}
  - name: "products"
    label: "Products"
    label_singular: "Product"
    description: "Colette Snow Media products"
    folder: "products"
    delete: true
    create: true
    fields:
    - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    files:
    - label: "Homepage"
      name: "home"
      file: "index.md"
      fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "default"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "text"}
    - label: "About Colette Snow"
      name: "about"
      file: "about-colette-snow-media.md"
      fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
    - label: "Services"
      name: "services"
      file: "services.md"
      fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
    - label: "Cookie Policy"
      name: "cookie-policy"
      file: "cookie-policy.md"
      fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
    - label: "Contact Form"
      name: "contact"
      file: "contact.html"
      fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "text"}
    - label: "Contact Form Thank You"
      name: "contact"
      file: "contact-thankyou.md"
      fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "text"}
    - label: "Error 404 Page"
      name: "error"
      file: "404.html"
      fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "default"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "text"}